### PR TITLE
added theme clock

### LINKED ISSUE #53: Add Theme Clock (Day 19)
**Reference:**
https://50projects50days.com/projects/theme-clock/

**Screenshots:**
image

### PR DESCRIPTION
**Pull request by KrishnaMoorthy12**
closes #53 

image

### CODE REVIEW

**Review by sank2000 — CHANGES_REQUESTED** [review]
animation should be continue ..(after 60 sec the needle animation is reseted)

i think you can fix that with animation direction

**Comment by KrishnaMoorthy12** [comment]
> animation should be continue ..(after 60 sec the needle animation is reseted)
> 
> i think you can fix that with animation direction

I don't think its possible at all.

**Comment by KrishnaMoorthy12** [comment]
Refer the original also. Ours is far better XD

**Review by sank2000 — APPROVED** [review]
cool

**Review by PranavGPR — APPROVED** [review]

**Pull request merged**
