### PR TITLE
Blurry Loading added Day 5

### PR DESCRIPTION
**Pull request by PranavGPR**
Check and merge it asap.

### CODE REVIEW

**Review by KrishnaMoorthy12 — CHANGES_REQUESTED** [review]
Throws the following warning: 
```
Warning: Invalid value for prop `scale` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
    at div
    at blurry-loading__TextContainer (/home/codespace/workspace/7days-50projects/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at div
    at blurry-loading__Container (/home/codespace/workspace/7days-50projects/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
    at BlurryLoading (webpack-internal:///./src/pages/blurry-loading.tsx:23:61)
    at App (webpack-internal:///./src/pages/_app.tsx:24:3)
    at AppContainer (/home/codespace/workspace/7days-50projects/node_modules/next/dist/next-server/server/render.js:25:748)
```

**Review by KrishnaMoorthy12 — CHANGES_REQUESTED** [review]
Also, I suggest adding an image of better quality

**Comment by PranavGPR** [comment]
> Throws the following warning:
> 
> ```
> Warning: Invalid value for prop `scale` on <div> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM. For details, see https://reactjs.org/link/attribute-behavior 
>     at div
>     at blurry-loading__TextContainer (/home/codespace/workspace/7days-50projects/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
>     at div
>     at blurry-loading__Container (/home/codespace/workspace/7days-50projects/node_modules/styled-components/dist/styled-components.cjs.js:1:18828)
>     at BlurryLoading (webpack-internal:///./src/pages/blurry-loading.tsx:23:61)
>     at App (webpack-internal:///./src/pages/_app.tsx:24:3)
>     at AppContainer (/home/codespace/workspace/7days-50projects/node_modules/next/dist/next-server/server/render.js:25:748)
> ```

I need to pass a function as a prop to a div so that i can use that in opacity reducing and blurring. Ideas are welcome.

**Comment by PranavGPR** [comment]
> Also, I suggest adding an image of better quality

It looked somewhat new to me so that I added it.

**Comment by KrishnaMoorthy12** [comment]
I have fixed the warning, I guess. Please review.

**Review by Lakshmi2k1 — APPROVED** [review]

**Pull request merged**
