### PR TITLE
wave form added (Day 8)

### LINKED ISSUE #67: Add Wave Form (Day 8)
**Reference:**
[here](https://50projects50days.com/projects/form-wave/)

### PR DESCRIPTION
**Pull request by sank2000**
closes #67

### CODE REVIEW

**Comment by KrishnaMoorthy12** [comment]
There is overlap of label and input text when user input is given. Fix this.

image

**Review by KrishnaMoorthy12 — CHANGES_REQUESTED** [review]
Fix the bug.

**Review by PranavGPR — APPROVED** [review]
Nice work! 👍

**Review by KrishnaMoorthy12 — CHANGES_REQUESTED** [review]
It works, but I noticed that input type of email is set to text. The way you had to solve this bug was using `:placeholder-visible`. When the user gives an invalid email id, the label will come back down on the current case when input type is set correctly.

**Review by KrishnaMoorthy12 — APPROVED** [review]
good job.

**Pull request merged**
