### PR TITLE
Added Instagram themed double-tap-like

### LINKED ISSUE #61: Add Double Click Heart (Day 29)
**Reference:**
https://50projects50days.com/projects/double-click-heart/

### PR DESCRIPTION
**Pull request by KrishnaMoorthy12**
closes #61 

**Screenshot**
image

### CODE REVIEW

**Review by sank2000 — CHANGES_REQUESTED** [review]
fix the initial render bug

**Comment by KrishnaMoorthy12** [comment]
the requested changes were made and few more fine-tuning is done

**Review by Lakshmi2k1 — APPROVED** [review]

**Comment by PranavGPR** [comment]
**The container having that image has some extra spaces. I was clicking outside of the image.**

image

**Review by PranavGPR — CHANGES_REQUESTED** [review]
https://github.com/benxene/7days-50projects/pull/68#issuecomment-739516924

**Kindly see this**

**Review by sank2000 — APPROVED** [review]
looks good 💥

**Comment by KrishnaMoorthy12** [comment]
> [#68 (comment)](https://github.com/benxene/7days-50projects/pull/68#issuecomment-739516924)
> 
> **Kindly see this**

BOY!!! That's not a bug, that's a feature.

**Comment by KrishnaMoorthy12** [comment]
The card will not change its dimensions based on content, at the same time, I cannot lose details in the image by cropping out.

**Review by PranavGPR — APPROVED** [review]

**Pull request merged**
