### PR TITLE
Hidden Search Widget Day 4 completed

### PR DESCRIPTION
**Pull request by PranavGPR**
Hidden Search Widget Day 4 has been completed

### CODE REVIEW

**Comment by KrishnaMoorthy12** [comment]
This PR reverts reviewed changed of `src/pages/rotating-navigation-animation.tsx`
Resolve and reopen

**Review by KrishnaMoorthy12 — CHANGES_REQUESTED** [review]
Here is the problem.

**Comment by PranavGPR** [comment]
Removed that file @KrishnaMoorthy12

**Review by Lakshmi2k1 — APPROVED** [review]

**Review by KrishnaMoorthy12 — COMMENTED** [review]
Good job @Lakshmi2k1 and @PranavGPR

**Comment by KrishnaMoorthy12** [comment]
Don't make a merge commit. Do Squash and merge to keep the commit history clean. 

@PranavGPR @Lakshmi2k1 @MohamedJakkariya

**Pull request merged**
